[package]
name = "embassy-rp-base"
version = "0.0.1"
edition = "2024"

[dependencies]
embassy-executor = { version = "0.9", features = [
    "arch-cortex-m",
    "executor-thread",
    "defmt",
] }
embassy-time = { version = "0.5", features = [
    "defmt",
    "defmt-timestamp-uptime",
] }
embassy-rp = { version = "0.10", features = [
    "defmt",
    "unstable-pac",
    "time-driver",
    "critical-section-impl",
] }
embassy-usb = { version = "0.6" }
defmt = "1.0"
cortex-m = { version = "0.7.6", features = ["inline-asm"] }
cortex-m-rt = "0.7.0"
critical-section = "1.1"
panic-probe = { version = "1.0", features = ["print-defmt"] }
static_cell = "2.1.1"
portable-atomic = { version = "1.13", features = ["critical-section"] }
heapless = { version = "0.9", features = ["defmt"] }
assign-resources = { git = "https://github.com/adamgreig/assign-resources", rev = "bd22cb7a92031fb16f74a5da42469d466c33383e" }
embassy-defmt-usb = { version = "0.0.1", features = ["global-logger"] }

[features]
default = ["rp235xa"]
rp235xa = ["embassy-rp/rp235xa"]
rp235xb = ["embassy-rp/rp235xb"]
rp2040 = ["embassy-rp/rp2040"]

[profile.release]
debug = 0
lto = true
opt-level = 'z'

[profile.dev]
debug = 2
lto = true
opt-level = "z"
