[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# Default runner using probe-rs.
runner = "probe-rs run --chip RP235x --protocol swd"

# Uncomment to deploy via picotool instead:
# runner = "picotool load -u -v -x --force"

[build]
target = "thumbv8m.main-none-eabihf" # RP2350x

[target.thumbv8m.main-none-eabihf]
linker = "rust-lld"
rustflags = [
    "-C", "link-arg=--nmagic",
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Tdefmt.x",
]

[env]
DEFMT_LOG = "info"
